In [6]:
import numpy as np

arr = np.arange(1, 31, 1)
matrix = arr.reshape(6,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [8]:
matrix[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [17]:
matrix[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [26]:
matrix[[2,3,4,5],[0,1,2,3]]


array([11, 17, 23, 29])