In [37]:
#dùng numpy để thao tác vs array
import numpy as np

#1 tạo array từ list (dùng array)
list = [1,2,3,4]
arr1 = np.array(list) 
arr1

#tạo array trực tiếp 
arr2 = np.array([1,2,3,4,5])
arr2

#2 tạo array dùng asarray (asararray là array nhưng ít properties)
arr3 = np.asarray(list)
#print(arr3)

#zeros: mảng có defaut values = 0
arr4 = np.zeros(5, dtype = 'i4') #5 phần tử, có kiểu là int 4 byte
#print(arr4)

#ones: mặc định là 1
arr5 = np.ones(6)
arr5

#tạo mảng dùng arange 
arr6 = np.arange(5, 20, 2) #mảng bắt đầu từ 5, kết thúc = 20, step = 2
arr6

#tạo mảng dùng linspace
arr7 = np.linspace(5, 100, 10, dtype = 'i4') #bắt đầu từ 5, kết thúc = 100, 10 phần từ, các phần tử cách nhau 1 khoảng = nhau
arr7

#tạo mảng ngẫu nhiên
arr8 = np.random.rand(10)  #mảng 10 phần tử giá trị ngẫu nhiên từ 0->1
arr8

arr9 = np.random.randint(5, 30, size = 5) #mảng 5 phần tử giá trị ngẫu nhiên từ 5->30
arr9

#arr10 là arr9 á :))) size có thể khai báo là tuble or int cũng dc
arr10 = np.random.randint(5, 30, size = (5,))
arr10

array([17, 22,  5, 12, 12])

In [12]:
### truy xuất

arr = arr10 = np.random.randint(5, 30, size = 10)
print(arr10)

#số phần tử của mảng
arr.shape[0]

#mảng với các phần tử trong khoảng từ 2 đến 5 (từ vị trí 2 -> 4 (5-1))
arr[2:5]

# 5 phần tử đầu tiên mảng bắt đầu từ 0 -> 4
arr[:5]

#mảng gồm phần tử từ vị trí thứ 5 đến hết
arr[5:]

#đảo ngược mảng
arr[::-1]

#lấy vị trí thứ 2 và 5
arr[2::5]
#mảng với các phần tử theo điều kiện
arr[arr > 10]
arr[(arr > 15) & (arr<25)]
arr[(arr > 15) | (arr<25)]

arr[arr % 2 == 0]

#dùng where hoặc extract
arrCondition = np.where((arr > 10) & (arr < 30))
arr[arrCondition]

#dùng extract
np.extract((arr % 2 == 0), arr)


[24 25  8  7  8  6 27  8  7 18]


array([0, 0, 0, 0, 0, 1, 0, 0])

In [ ]:
###truy xuất = slice

arr = np.arange(0,11,1)
print(arr)

arr[slice(3,6)] # <=> arr[3:6]

arr[slice(2,7,2)] #lấy vị trí 2->6, step = 2 i = (2, 4, 6)


### Thêm, xóa phần tử 

In [77]:
arr = np.random.randint(5, 30, size = 10)
print(arr)

###append và delete, insert tạo ra bản sao nên phải gán lại giá trị cho arr
#thêm vào cuối array
arr = np.append(arr, 200)
arr

##thêm vào vị trí bất kỳ
arr = np.insert(arr, 3, [100,200]) #thêm 100 và 200 vào vị trí thứ 3 (và 4)
arr

#xóa phần tử tại vị trí index = 1 và 2
arr = np.delete(arr, [1,2])
arr

[ 6 11 18 20 23  6 16  5 18 19]


array([  6, 100, 200,  20,  23,   6,  16,   5,  18,  19, 200])

In [6]:
###broadcasting
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([10, 20, 30])

#cộng các phần tử arr1 cho 5
print(arr1)
arr1 +=4
arr1

arr1 += arr2
arr1

[1 2 3]


array([15, 26, 37])

In [22]:
#statistic
arr = np.random.randint(1, 50, size = 10)
print(arr)
np.amin(arr) # <=> arr.min()

arr.max() #<=> np.arr.max()

#giá trị trung bình số học ...
arr.mean() #<=> np.arr.mean()

#sort
arr.sort()
arr

##
arr = np.sort(arr)
arr

[20 36 47 40 39  1 49 15 14 18]


array([ 1, 14, 15, 18, 20, 36, 39, 40, 47, 49])

# Mảng 2 chiều

In [30]:
#khai báo mảng nhiều chiều
list = [[1,2,3], [3,5,1], [-4,2,5]]
arr3 = np.array(list)
arr3

#cách 2
arr4 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr4

#mảng 2 chiều có kích thước 4*3
arr5 = np.zeros([4,3], dtype = int)
arr5

arr6 = np.ones([3,4], int)
arr6

#mảng 2 chiều random
arr7 = np.random.rand(4, 5)
arr7

arr8 = np.random.randint(-19, 50, size = (3,4)) #3 dòng, 4 cột
arr8

array([[ -3, -12, -10, -15],
       [ 22, -17,  41,  26],
       [ 30,   0,  12,   7]])

In [ ]:
#ndmin đơn giản là số chiều của array đó
list = [[1,2,3], [3,5,1], [-4,2,5]]
arr3 = np.array(list, ndmin = 2)

#dtype đơn giả là kiểu dữ liệu của nó, int32 (i4) là int 4byte á
arr4 = np.array(list, dtype = np.int32)
arr5 = np.array(list, dtype = 'i4')
arr5

##### kích thước của mảng

In [55]:
matrix = np.random.randint(-10, 20, size = (4,5))
print(matrix)

#size of matrix = shape => return tuble (4,5)
matrix.shape


[[ 3 17 12 -8 -8]
 [ 3  3 -9 -4 11]
 [ 3 10 17 15 14]
 [ 3 10  8  4 18]]


4

#### truy xuất

In [22]:
import numpy as np
matrix = np.array([[3,5,-3,6], [6,3,-5,-3], [0,4,-10,2], [4,6,11,-11]])
print(matrix)

#get matrix[2][3]
matrix[2][3]
matrix[2,3]

#get array dòng 0, cột từ 1->3 (là [5, -3, 6])
matrix[0, 1:4]

#lấy các giá trị -10, 2, 11, -11 (lấy dòng thứ 2 đến hết và cột thứ 2 đến hết)
matrix[2:, 2:]

matrix[0:3, 1:]

matrix[0::3, 0::3]

[[  3   5  -3   6]
 [  6   3  -5  -3]
 [  0   4 -10   2]
 [  4   6  11 -11]]


array([[  3,   6],
       [  4, -11]])

### chuyển array 1 chiều thành array 2 chiều (matrix)

In [29]:
arr = np.array([3,5,-3,6, 6,3,-5,-3, 0,4,-10,2, 4,6,11,-11])
arr

#chuyển từ mảng 1 chiều qua mảng 2 chiều
arr.shape = (4,4) #4*4 = 16 ( = arr.size)
arr

matrix = arr.reshape(4,4)
matrix

##chuyển mảng 2 chiều thành 1 chiều
arr2 = matrix.ravel()
arr2

array([  3,   5,  -3,   6,   6,   3,  -5,  -3,   0,   4, -10,   2,   4,
         6,  11, -11])

In [50]:
matrix1 = np.random.randint(-10, 20, (4,5))
matrix1

matrix2 = np.random.randint(-10, 20, (4,5))
matrix2

matrix1 + matrix2



array([[17, 20, -6, 26,  7],
       [ 1, 17,  6, 17, 20],
       [11, -4, 14, 28,  5],
       [18, 21, 25, 11, 11]])

In [59]:
matrix = np.array([[1,2,3], [4,5,6],[None, 4,5]])
if matrix.any() is None:
    print("1")

### tìm max, min trên dòng và cột
# dùng axis khi liên quan đến value trên cột or dòng

In [4]:
import numpy as np
matrix1 = np.random.randint(-10, 20, (4,5))
print(matrix1)

#max theo từng dòng
matrix1.max(axis=0)

#min theo từng cột
matrix1.min(axis=1)

[[ 12  -9   0   4   0]
 [ 15   6  -4   0  12]
 [  1  14  19  14 -10]
 [ -3  -4  13   9 -10]]


array([ -9,  -4, -10, -10])

## độ lệch chuẩn (đặc trưng cho độ phân tán của dữ liệu) = căn của phương sai

### phương sai: var = $\sum_{i = 0}^{n} $$\frac{(xi - \overline{x})^2}{n}$
### std = sqrt(var)

vd: matrix = (1 2
              3 4)
              
=> n = 4 (có 4 số)
$\overline{x}$ = (1+2+3+4)/n = 10/4 = 2.5
=> var = $\frac{(1 - 2.5)^2 + (2 - 2.5)^2 + (3 - 2.5)^2 + (4 - 2.5)^2}{4}$ = $\frac{2.25 + 0.25 + 0.25 + 2.25}{4}$ = 1.25
=> std = sqrt(var) = sqrt(1.25) = 1.118
             


In [11]:
matrix = np.array([
    [1,2],
    [3,4]
])

print(matrix)

print('độ lệch chuẩn std:', matrix.std()) # = np.std(matrix)
print('phương sai var:', np.var(matrix))

matrix.std(axis = 1) #tính theo dòng 
matrix.var(axis = 1) #

[[1 2]
 [3 4]]
độ lệch chuẩn std: 1.118033988749895
phương sai var: 1.25


array([0.25, 0.25])

In [13]:
height = np.array([173, 180, 155, 168])
weight = np.array([64, 70, 55, 60])

print('Hệ số tương quan corrcoef: \n', np.corrcoef(height, weight))

Hệ số tương quan corrcoef: 
 [[1.         0.97597629]
 [0.97597629 1.        ]]


## kiểu object tự định nghĩa trong np (class á:)) 
### tạo kiểu dtype

In [15]:
dStaff = np.dtype([('Name', 'U10'), ('Age', 'i4'), ('salary', '<f8')] )
dStaff

dtype([('Name', '<U10'), ('Age', '<i4'), ('salary', '<f8')])

In [27]:
data = [
    ('Trung', 22, 3000),
    ('Quan', 25, 400),
    ('Minh', 21, 500)
]

dsnv = np.array(data, dtype=dStaff)
dsnv

array([('Trung', 22, 3000.), ('Quan', 25,  400.), ('Minh', 21,  500.)],
      dtype=[('Name', '<U10'), ('Age', '<i4'), ('salary', '<f8')])

In [28]:
dsnv = np.sort(dsnv, order = 'Age')
dsnv

array([('Minh', 21,  500.), ('Trung', 22, 3000.), ('Quan', 25,  400.)],
      dtype=[('Name', '<U10'), ('Age', '<i4'), ('salary', '<f8')])

## lấy phần giao giữa 2 mảng (các phần tử xuất hiện mảng 1 và mảng 2)

In [34]:
arr1 = np.array([1,2,4,6,-4,1,43,2,7,8, 100])
arr2 = np.array([1,2,4,6,6,8,-2,5,2,22,199])

#lấy phần giao giữa 2 mảng (các phần tử xuất hiện mảng 1 và mảng 2) 
#và giá trị là unique
# arr3 = arr1 giao arr2
arr3 = np.intersect1d(arr1, arr2)
arr3

#lấy phần hiệu giữa 2 mảng (lấy các phần tử có trong arr1 mà ko có trong arr2 mà)
# arr4 = arr1 - arr2
arr4 = np.setdiff1d(arr1, arr2)
arr4

array([ -4,   7,  43, 100])