In [30]:
import numpy as np
import math

In [31]:
#hàm check số x có phải là số chính phương hay không
def isPerfectSquare(x):
    sq_root = int(math.sqrt(x))
    if (sq_root * sq_root) == x:
        return True
    return False

### Câu 1: 
Xây dựng hàm kiểm tra số chính phương với tham số truyền vào là mảng def
kiem_tra_so_chinh_phuong(mang) để kiểm tra mảng truyền vào có phần tử nào
là số chính phương không (số chính phương là một số nguyên và có căn bậc 2 cũng là
một số nguyên. Vd : 9 là số chính phương (căn bậc 2 của 9 = 3 là một số nguyên).
Kết quả trả về mảng các giá trị True hoặc False tương ứng các phần tử trong mảng có
phải là số chính phương hay không.


In [32]:
#hàm ktra mảng truyền vào có phần tử nào là số chính phương không
def kiem_tra_so_chinh_phuong(mang):
    tempMatrix = np.empty([mang.shape[0], mang.shape[1]], dtype = bool)
    for i in range(mang.shape[0]):
        for j in range(mang.shape[1]):
            tempMatrix[i][j] = isPerfectSquare(mang[i][j])
    return tempMatrix

### Câu 2:
Phát sinh mảng 2 chiều có kích thước 4x4 với các phần tử có giá trị phát sinh ngẫu
nhiên từ 1 đến 100.

In [33]:
matrix = np.random.randint(1, 20, [4,4])
print(matrix)

[[10 14 12 13]
 [10  9 18  4]
 [ 6  8  3 18]
 [10  3  9  7]]


### Câu 3:
Kiểm tra và xuất ra danh sách các phần tử trong mảng là số chính phương (sử dụng
điều kiện lọc trực tiếp).

In [34]:
check = kiem_tra_so_chinh_phuong(matrix)
print(check)

[[False False False False]
 [False  True False  True]
 [False False False False]
 [False False  True False]]


In [35]:
#lọc dữ liệu trực tiếp từ mảng với hàm kiem_tra_so_chinh_phuong
#check = kiem_tra_so_chinh_phuong(matrix)
print(matrix[check])

[9 4 9]


### Câu 4 
In ra danh sách các phần tử là số chính phương theo định dạng : [(chỉ số dòng, chỉ
số cột), giá trị]

In [36]:
#thông tin về vị trí của số chính phương
#vd: indexList = [[0, 1, 2], [3, 2, 1]] nghĩa là số chính phương ở vị trí matrix[0][3], matrix[1][2] và matrix[2][1]
indexList = [i.tolist() for i in np.where(check)]

resList = [] #list các phần tử là số chính phương theo định dạng : [(chỉ số dòng, chỉ số cột), giá trị]

for i in range(len(indexList[0])):
    temp = []
    temp.append((indexList[0][i], indexList[1][i]))
    temp.append(matrix[indexList[0][i]][indexList[1][i]])
    
    resList.append(temp)
    
resList


[[(1, 1), 9], [(1, 3), 4], [(3, 2), 9]]

### Câu 5:
Thay thế giá trị của các phần tử không phải là số chính phương trong mảng bằng 0.

In [37]:
#cách 1: dùng where
matrix = np.where(check, matrix, 0)
print(matrix)

[[0 0 0 0]
 [0 9 0 4]
 [0 0 0 0]
 [0 0 9 0]]


In [51]:
# cách 2:
#matrix2 != matrix ở trên
matrix2 = np.random.randint(1, 20, [4,4])
print(matrix2)

check2 = kiem_tra_so_chinh_phuong(matrix2)
check2

matrix2[check2 == False] = 0
matrix2

[[ 1 18  6  8]
 [13 19  9  6]
 [ 9  8 15 17]
 [ 1  3 16  2]]


array([[ 1,  0,  0,  0],
       [ 0,  0,  9,  0],
       [ 9,  0,  0,  0],
       [ 1,  0, 16,  0]])